theme: jekyll-theme-tactile
title: XFS4IoT specification preview
exclude: ["ReadMe.md", "Rakefile", "changelog.md", "License.md"]
production_url : https://xfs4iot.github.io/Specifications-Preview.github.io
BASE_PATH : https://xfs4iot.github.io/Specifications-Preview.github.io
